language: cpp
compiler:
- gcc
before_install:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/install_boost.sh && chmod +x install_boost.sh
  && ./install_boost.sh libboost-filesystem1.55-dev libboost-system1.55-dev
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/update_gcc_version.sh && chmod +x update_gcc_version.sh
  && ./update_gcc_version.sh 4.9
before_script:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/setup_biicode_project.py && chmod +x setup_biicode_project.py
  && ./setup_biicode_project.py
script:
- bii find
- bii cpp:configure
- bii cpp:build
- "../../../bin/messmer_blobstore_test_main"
#deploy:
#  provider: biicode
#  user: messmer
#  password:
#    secure: pw-hash
#  on:
#    branch: develop
#    repo: smessmer/tempfile
