language: cpp
compiler:
- gcc
before_install:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/update_gcc_version.sh
  && chmod +x update_gcc_version.sh
  && ./update_gcc_version.sh 4.9
  && rm update_gcc_version.sh
before_script:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/setup_biicode_project.py
  && chmod +x setup_biicode_project.py
  && ./setup_biicode_project.py
  && rm setup_biicode_project.py
script:
- bii find
- bii cpp:configure
- bii cpp:build -- -j2
- "../../../bin/messmer_blockstore_test_main"
deploy:
  provider: biicode
  user: ${BII_USERNAME}
  password:
    secure: ${BII_PASSWORD}
  on:
    branch: develop

